export { default as VK } from '../assets/icon/vk.svg'
export { default as Instagram } from '../assets/icon/instagram.svg'
export { default as Telegram } from '../assets/icon/telegram.svg'
export { default as Gmail } from '../assets/icon/gmail.svg'

export { default as About } from '../assets/icon/about.svg'
export { default as Tour } from '../assets/icon/tour.svg'
export { default as Vip } from '../assets/icon/vip.svg'
export { default as Review } from '../assets/icon/review.svg'
export { default as Workspace } from '../assets/icon/workspace.svg'